#!/bin/python3
import sys

test_case = input()
cases = []
total = 0

def is_integer(n):
    try:
        float(n)
    except ValueError:
        return False
    else:
        return float(n).is_integer()

if(is_integer(test_case) == False):
    sys.exit()
else:
    test_case = int(test_case)

if(test_case < 1 or test_case > 10**5):
    sys.exit()

for x in range(0,test_case):
    number = int(input())
    
    if(number < 1 or number > 10**9):
        sys.exit()
    else:
        cases.append(number)

    
for y in range(0,len(cases)):
    for counter in range(3,cases[y]):
        if (counter % 3 == 0 or counter % 5 == 0):
            total = total + counter

    print(total)
    total = 0
